Feature/payment system/init
anishchenkoivan/hotel-app pull request #7
Opened 2024-12-14 18:24 UTC by iv4n-t3a

2024-12-14 18:40 UTC, anishchenkoivan requested changes
Тут еще нет бдшки, откуда можно было бы таскать информацию, это тоже нехорошо. Долго что-либо в памяти хранить может быть неэффиективно и небезопасно

2024-12-14 18:40 UTC, anishchenkoivan commented on payment-system/internal/app/app.go
> +	if err := app.server.Shutdown(shutdownCtx); err != nil {
Если это возвращает error, то grpc не сделает stop(), что нехорошо. Кроме того, Shutdown() - блокирующий вызов, так что GracefulStop возможно, займет больше времени, чем ожидается, потому что его время выполнения не зависит от контекста. Сделай выключение многопоточным и ограниченным по времени.

2024-12-14 18:40 UTC, anishchenkoivan commented on payment-system/internal/app/handlers/grpc_add_payment.go
> +package handlers
Как будто бы весь этот файл вроде бы отделен, но не особо соответствует требованиям к разделенности архитектуры по слоям. Нет отдельного service

2024-12-14 18:40 UTC, anishchenkoivan commented on payment-system/internal/app/handlers/grpc_add_payment.go
> +		_, exists := s.bookingEntityByHash[token]
У этой штуки точно синхронизация не полетит? Просто мапа внутри горутины, после того, как ранее был вызван my.Unlcok() не внушает доверия

2024-12-14 19:03 UTC, iv4n-t3a commented
стоит добавить что директорию `cmd/payment-system` надо переименовать в `cmd/paymentsystem`

2024-12-14 19:04 UTC, iv4n-t3a commented
+на каждый grpc запрос создается новый клиент. Какая-то странная дичь

2024-12-15 14:49 UTC, Inteshil commented
из оперативки на постгрес переедем в другой ветке, если переедем конечно

2024-12-15 15:07 UTC, anishchenkoivan approved these changes

2024-12-15 15:16 UTC, merged